/*
    Needed Mods:
    - None

    Optional Mods:
    - None
*/

// Civilian classnames.
civilians = [
    "Aegis_C_Man_CargoPilot_lxWS_F", 
    "C_Djella_01_lxWS", 
    "C_Djella_02_lxWS", 
    "C_Djella_03_lxWS", 
    "C_Djella_04_lxWS", 
    "C_Djella_05_lxWS", 
    "C_Tak_02_A_lxWS", 
    "C_Tak_02_B_lxWS", 
    "C_Tak_02_C_lxWS", 
    "C_Tak_03_A_lxWS", 
    "C_Tak_03_B_lxWS", 
    "C_Tak_03_C_lxWS", 
    "C_Tak_01_A_lxWS", 
    "C_Tak_01_B_lxWS", 
    "C_Tak_01_C_lxWS", 
    "Aegis_C_Farmer_01_lxws_F", 
    "Aegis_C_Pilot_RF_lxWS", 
    "Aegis_C_Man_Paramedic_01_lxWS_F", 
    "Aegis_C_Man_Pilot_lxWS_F", 
    "Aegis_C_Man_UtilityWorker_01_lxWS_F", 
    "C_IDAP_Man_AidWorker_01_F", 
    "C_IDAP_Man_AidWorker_07_F", 
    "C_IDAP_Man_AidWorker_08_F", 
    "C_IDAP_Man_AidWorker_09_F", 
    "C_IDAP_Man_AidWorker_02_F", 
    "C_IDAP_Man_AidWorker_05_F", 
    "C_IDAP_Man_AidWorker_06_F", 
    "C_IDAP_Man_AidWorker_04_F", 
    "C_IDAP_Man_AidWorker_03_F", 
    "C_IDAP_Man_EOD_01_F", 
    "C_IDAP_Pilot_RF", 
    "C_IDAP_Man_Paramedic_01_F", 
    "C_IDAP_Pilot_01_F", 
    "C_IDAP_Man_UAV_06_antimine_F", 
    "C_IDAP_Man_UAV_01_F", 
    "C_IDAP_Man_UAV_06_F", 
    "C_IDAP_Man_UAV_06_medical_F", 
    "C_IDAP_Man_UGV_02_Demining_F",
    "C_Story_EOD_01_F"
];

// Civilian vehicle classnames.
civilian_vehicles = [
    "Aegis_C_Van_01_fuel_Argana_F", 
    "Aegis_C_Hatchback_01_Argana_F", 
    "Aegis_C_Hatchback_01_sport_Argana_F", 
    "Aegis_C_Offroad_02_lxWS", 
    "Aegis_C_Truck_02_cargo_Argana_F", 
    "Aegis_C_Truck_02_flatbed_Argana_F", 
    "Aegis_C_Truck_02_fuel_Argana_F", 
    "Aegis_C_Truck_02_racing_Argana_F", 
    "Aegis_C_Truck_02_box_Argana_F", 
    "Aegis_C_Truck_02_transport_Argana_F", 
    "Aegis_C_Truck_02_covered_Argana_F", 
    "Aegis_C_Offroad_lxWS", 
    "Aegis_C_Quadbike_01_lxWS", 
    "Aegis_C_Pickup_lxWS", 
    "Aegis_C_Pickup_Covered_lxWS", 
    "Aegis_C_SUV_01_lxWS", 
    "Aegis_C_Van_01_transport_Argana_F", 
    "Aegis_C_Van_01_box_Argana_F", 
    "Aegis_C_Van_02_medevac_Argana_F", 
    "Aegis_C_Van_02_vehicle_Argana_F", 
    "Aegis_C_Van_02_Service_Argana_F", 
    "Aegis_C_Van_02_transport_Argana_F",  
    "C_IDAP_Offroad_02_unarmed_F", 
    "C_IDAP_Truck_02_cargo_lxWS", 
    "C_IDAP_Truck_02_flatbed_lxWS", 
    "C_IDAP_Truck_02_box_lxWS", 
    "C_IDAP_Truck_02_transport_F", 
    "C_IDAP_Truck_02_F", 
    "C_IDAP_Truck_02_water_F", 
    "C_IDAP_Offroad_01_F", 
    "C_IDAP_Offroad_lxWS", 
    "C_IDAP_Pickup_rf", 
    "C_IDAP_Pickup_covered_rf", 
    "C_IDAP_Pickup_fuel_rf", 
    "C_IDAP_Pickup_water_rf", 
    "C_IDAP_Van_02_medevac_F", 
    "C_IDAP_Van_02_vehicle_F", 
    "C_IDAP_Van_02_transport_F"
];
